const USERS_LOAD = "app/users/LOAD";
const USERS_LOAD_SUCCESS = "app/users/LOAD_SUCCESS";
const USERS_CREATE = "app/users/CREATE";
const USERS_CREATE_SUCCESS = "app/users/CREATE_SUCCESS";

export { USERS_LOAD, USERS_LOAD_SUCCESS, USERS_CREATE, USERS_CREATE_SUCCESS };
